# Generated by Django 3.0.8 on 2020-07-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qaa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('j', 'java'), ('p', 'python'), ('c', 'c_prog')], max_length=1)),
                ('question', models.CharField(max_length=300)),
                ('ans', models.TextField()),
            ],
        ),
    ]
